// Auto-builds the music player's playlist from whatever audio lives in
// public/build/assets/songs/.
//
//   Filename convention:  "Artist - Title.mp3"
//     -> by   (static line)   = Artist        e.g. "sewerslvt"
//     -> name (looping title) = Title         e.g. "Mr. Kill Myself"
//   If there's no " - " in the name, the whole filename becomes the title
//   and the artist falls back to "kumuii".
//
//   Album cover:  drop an image with the SAME base name in songs/covers/,
//   e.g.  songs/covers/sewerslvt - Mr. Kill Myself.png
//   (any of .png .jpg .jpeg .webp .gif). If none is found it uses the
//   default album-cover.png.
//
// Writes public/build/tracks.js (window.KUMUII_TRACKS), which profile.js reads.
// Runs automatically before every build (the "prebuild" npm hook); run it any
// time with:  npm run tracks

import { writeFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const songsDir = join(root, 'public', 'build', 'assets', 'songs');
const coversDir = join(songsDir, 'covers');
const outPath = join(root, 'public', 'build', 'tracks.js');

const AUDIO_EXT = /\.(mp3|ogg|wav|m4a|flac)$/i;
const IMG_EXT = ['.png', '.jpg', '.jpeg', '.webp', '.gif'];
const DEFAULT_COVER = 'build/assets/album-cover.png';

// ----------------------------------------------------------------------
// MANUAL PLAYLIST ORDER — rearrange these lines to set the order.
// Use the file's base name (no .mp3). Songs listed here play in this exact
// order; any song in songs/ that's NOT listed gets appended at the end in
// alphabetical order (so a new drop-in never silently disappears).
// ----------------------------------------------------------------------
const ORDER = [
  'sewerslvt - Mr. Kill Myself',
  'Tommy february6 - je taime ★ je taime',
  'She Wants Revenge - These Things',
  'TV Girl - The Blonde',
  'らくらく安楽死',
  'everytime-we-touch',
  'Panchiko - All They Wanted',
  'Clarion - Cover Me',
  'Dominurmom - Remember You',
  'zhanulka - ток',
  '18hzr - mental disorder',
  '2hollis - cliche',
  'CUPSIZE - розовая могила',
  'Пошлая Молли - Райские цветы',

];

let files = [];
try {
  files = readdirSync(songsDir);
} catch (err) {
  console.error('[gen-tracks] could not read', songsDir, '-', err.message);
  process.exit(0); // don't fail the build over the playlist
}

let covers = [];
try {
  covers = readdirSync(coversDir);
} catch (e) { /* covers folder optional */ }

const baseName = f => f.replace(AUDIO_EXT, '').trim();

function findCover(base) {
  for (const ext of IMG_EXT) {
    const hit = covers.find(c => c.toLowerCase() === (base + ext).toLowerCase());
    if (hit) return 'build/assets/songs/covers/' + encodeURIComponent(hit);
  }
  return DEFAULT_COVER;
}

function parse(file) {
  const base = baseName(file);
  const i = base.indexOf(' - ');
  if (i === -1) return { name: base, by: 'kumuii' };
  return { name: base.slice(i + 3).trim(), by: base.slice(0, i).trim() };
}

const tracks = files
  .filter(f => AUDIO_EXT.test(f) && !f.startsWith('.'))
  .map(file => {
    const { name, by } = parse(file);
    return {
      name,
      by,
      src: 'build/assets/songs/' + encodeURIComponent(file),
      cover: findCover(baseName(file)),
      _base: baseName(file),
    };
  });

// apply manual ORDER; unlisted songs go to the end, alphabetical
const rank = b => { const i = ORDER.indexOf(b); return i === -1 ? Infinity : i; };
tracks.sort((a, b) => {
  const ra = rank(a._base), rb = rank(b._base);
  if (ra !== rb) return ra - rb;
  return a._base.localeCompare(b._base); // tie-break for unlisted songs
});
tracks.forEach(t => delete t._base);

const out =
  '// AUTO-GENERATED by scripts/gen-tracks.mjs — do not edit by hand.\n' +
  '// Add songs: drop "Artist - Title.mp3" in public/build/assets/songs/,\n' +
  '// optional cover with the same name in songs/covers/, then run `npm run tracks`.\n' +
  'window.KUMUII_TRACKS = ' + JSON.stringify(tracks, null, 2) + ';\n';

writeFileSync(outPath, out);
console.log('[gen-tracks] wrote ' + tracks.length + ' track(s) to public/build/tracks.js');
